### ISSUE TITLE
游戏素材文件的规格 Specification for assets files

### ISSUE THREAD

**Issue by Wang-Ji20** [Cimetiere-des-Innocents/Mutemaanpa#1]
通常来说游戏素材不能使用程序语言硬编码, 因此剧本可以使用:
1. Lisp S-expression
2. Lua
3. 自定义文件格式

**Comment by Chlamydomonos** [comment]
邪恶，剧本至少应该是JavaScript，而且允许Typescript，剧本的加载由vite之外的自定义途径完成，这可以避免剧本与引擎硬编码在一起
